# Generated by Django 5.1.1 on 2024-10-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
